### ISSUE TITLE
document 0.3 changes and finalize release

### ISSUE THREAD

**Issue by pietroppeter** [pietroppeter/nimib#85]
**edit**: consolidated a few comments with todo
**edit 2**: changed my mind again, release of 0.3 will require only to document past changes in order to be completed

having completed the breaking change:
- [x] make `codeAsInSource` the default and `codeFromAst` an option, see #94 

the only really required thing in order to release 0.3 is:

- [ ] document new stuff (and also stuff from 0.2 minor versions), see #81 and recent PRs
  - [ ] added a new newNbSlimBlock and newNbCodeBlock
  - [ ] nbText now does not read code
  - [ ] new nbTextWithCode that does read code
  - [ ] config utils for a theme such as nimibook
  - [ ] trim readme and it will NOT to depend on index.nim
  - [ ] add to readme a deploy section which documents how to deploy with GitHub pages
  - [ ] make links in docs relative so that they work in deploy preview (already done in js/karax pr, see)
  - [ ] nbRawOutput

all this other stuff can be safely added in 0.3.x updates, I will create issues for each one of them and grouped them in a project/milestone.
- [ ] put back highlighting js #68
- [ ] put back untyped nbFile (see discussion in #34)
- [ ] add test for nbFile
- [ ] add test for nbImage
- [ ] add also nbAudio and nbVideo (with tests) and a media example
- [ ] add nbShell (wraps osproc.execCmdEx) (completes #34)
- [ ] add a document that shows how to use `nbPython` and maybe offers `nbPythonCode` implementation (see [this commit](https://github.com/pietroppeter/nimib/pull/83/commits/fedd4c68baab1c849505c3d5ec455af17c77dac9)) as a novelty (and also as a way to show how to do a custom code block)
- [ ] rethink/review markdown related stuff (both for markdown backend and for converting to markdown) and in general change the documentation:
  - [ ] readme.md will not be generated anymore from nim (too clumsy to fix a small typo in readme) - instead index.nim might depend on readme (partial inclusion).
  - [ ] add a md2html.nim file that converts a given md file to html using default theme (as it happens in nimibook)
  - [ ] this same md2html file will also be saved with markdown backend
  as md2html.md
  - [ ] and md2html.md will be converted itself as a md2html2md2html.html (which might be slightly different from md2html)
- [ ] config file found should report path relative to initDir
- [ ] NbBlock as a container: I think this can be done without breaking changes and it opens up many possibilities of use cases.

**Comment by pietroppeter** [comment]
updates on stuff to do:
- [ ] put back untyped nbFile (see discussion in #34)
- [ ] trim readme not to depend on index.nim
- [ ] add to readme a deploy section which documents how to deploy with GitHub pages

**Comment by pietroppeter** [comment]
- [ ] add a document that shows how to use `nbPython` and maybe offers `nbPythonCode` implementation (see [this commit](https://github.com/pietroppeter/nimib/pull/83/commits/fedd4c68baab1c849505c3d5ec455af17c77dac9)) as a novelty (and also as a way to show how to do a custom code block)
